# Generated by Django 3.2.13 on 2022-05-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='highlights',
            field=models.TextField(blank=True, verbose_name='Article Highlights'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is Complete'),
        ),
        migrations.AddField(
            model_name='article',
            name='time_read_minutes',
            field=models.IntegerField(default=0, verbose_name='Time Read Seconds'),
        ),
    ]
