# Generated by Django 3.2.13 on 2022-06-22 20:40

from django.db import migrations, models


def migrate_boolean_to_datetime(apps, schema_editor):

    Article = apps.get_model('tasks', 'Article')

    for article in Article.objects.all():

        if article.is_complete:
            article.completed_at = article.created_at
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_article_highlight_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='completed_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Completed At'
            ),
        ),
        migrations.RunPython(migrate_boolean_to_datetime),
        migrations.RemoveField(
            model_name='article',
            name='is_complete',
        ),
    ]
